spring:
  application:
    name: eureka-server
server:
  undertow:
    buffer-size: 1024
    direct-buffers: true
eureka:
  instance:
    prefer-ip-address: true
  server:
    wait-time-in-ms-when-sync-empty: 0
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      #,https://localhost:8762/eureka/,https://localhost:8763/eureka/
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: localhost

---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: localhost

---
spring:
  profiles: peer3
server:
  port: 8763
eureka:
  instance:
    hostname: localhost

