server:
  port: 7777
spring:
  profiles:
    include: common
  application:
    name: org-server
  datasource:
    url: jdbc:mysql://huaweioldtan:13306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: oldtan